#!/usr/bin/env bash
# Regenerates Plugin/types/ampcode-plugin.d.ts from the plugin API docs that
# ship with the installed Amp CLI, so `bun x tsc` can type-check the bridge.
set -euo pipefail
out=Plugin/types/ampcode-plugin.d.ts
mkdir -p "$(dirname "$out")"
{
  echo "// Generated by Scripts/refresh-plugin-types.sh from \`amp plugins show-docs\`."
  echo "// Do not edit; rerun the script after upgrading Amp."
  amp plugins show-docs | sed -n "/^declare module '@ampcode\/plugin'/,\$p"
} > "$out"
echo "wrote $out ($(wc -l < "$out") lines)"
